spring:
  application:
    name: secondStart
  devtools:
    livereload:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console